# Generated by Django 3.1.5 on 2021-04-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='posts',
            field=models.ManyToManyField(blank=True, to='eduHub.Post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, to='eduHub.Course'),
        ),
    ]
