# Generated by Django 3.1.5 on 2021-05-03 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduHub', '0004_auto_20210428_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, default='0', to=settings.AUTH_USER_MODEL),
        ),
    ]
